remote_theme: jonahjnewton/TDVaultSite

title:               TD Vault
tagline:             '3D Animation & VFX Programming Tips'
description:         'A space for me to ramble and keep notes on Animation/VFX programming concepts. By <a href="https://jonahnewton.com.au">Jonah Newton</a>'
url:                 http://tdvault.jonahnewton.com.au
baseurl:             ''
paginate:            5
permalink:           pretty
