remote_theme: jonahjnewton/TDVaultSite

title:               TD Vault
tagline:             'Notes on Programming for 3D Animation & VFX'
description:         'Notes on Programming for 3D Animation & VFX. My learnings as a Pipeline TD that may not be available or fully documented online. By <a href="https://jonahnewton.com.au">Jonah Newton</a>'
paginate:            5
permalink:           pretty

baseurl: ""

# About/contact
author:
  name:              Jonah Newton
  url:               https://jonahnewton.com.au
  email:             jonah@jonahnewton.com.au
